### ISSUE TITLE
Conflicts between mockerena and werkzeug

### ISSUE THREAD

**Issue by NeolithEra** [FanThreeSixty/mockerena#18]
Hi, users are unable to run **_mockerena_** due to dependency conflict with _**werkzeug**_ package. As shown in the following full dependency graph of **_mockerena_**, **_eve_** requires _**werkzeug ==0.15.4**_，while **_flask_** requires _**werkzeug >=0.15**_.

According to pip’s _“first found wins”_ installation strategy, _**werkzeug 0.16.0**_ is the actually installed version. However, _**werkzeug 0.16.0**_ does not satisfy _**==0.15.4**_.

### Dependency tree-----------
```
mockerena - 1.2.0
| +- eve(install version:0.9.2 version range:>=0.9.0)
| | +- cerberus(install version:1.3.2 version range:>=1.1)
| | | +- setuptools(install version:42.0.2 version range:*)
| | +- events(install version:0.3 version range:<0.4,>=0.3)
| | +- flask(install version:1.1.1 version range:>=1.0)
| | | +- click(install version:7.0 version range:>=5.1)
| | | +- itsdangerous(install version:1.1.0 version range:>=0.24)
| | | +- jinja2(install version:2.10.3 version range:>=2.10.1)
| | | | +- markupsafe(install version:1.1.1 version range:>=0.23)
| | | +- werkzeug(install version:0.15.4 version range:>=0.15)
| | +- pymongo(install version:3.9.0 version range:>=3.7)
| | +- simplejson(install version:3.17.0 version range:>=3.3.0,<4.0)
| | +- werkzeug(install version:0.15.4 version range:==0.15.4)
| +- exrex(install version:0.10.5 version range:>=0.10.5)
| +- faker(install version:3.0.0 version range:>=2.0.0)
| +- flasgger(install version:0.9.4.dev2 version range:>=0.9.0)
| | +- flask(install version:1.1.1 version range:>=0.10)
| | | +- click(install version:7.0 version range:>=5.1)
| | | +- itsdangerous(install version:1.1.0 version range:>=0.24)
| | | +- jinja2(install version:2.10.3 version range:>=2.10.1)
| | | | +- markupsafe(install version:1.1.1 version range:>=0.23)
| | | +- werkzeug(install version:0.15.4 version range:>=0.15)
| | +- jsonschema(install version:3.2.0 version range:>=3.0.1)
| | +- mistune(install version:2.0.0a1 version range:*)
| | +- pyyaml(install version:5.2 version range:>=3.0)
| | +- six(install version:1.13.0 version range:>=1.10.0)
| +- flask(install version:1.1.1 version range:>=1.1.0)
| | +- click(install version:7.0 version range:>=5.1)
| | +- itsdangerous(install version:1.1.0 version range:>=0.24)
| | +- jinja2(install version:2.10.3 version range:>=2.10.1)
| | | +- markupsafe(install version:1.1.1 version range:>=0.23)
| | +- werkzeug(install version:0.16.0 version range:>=0.15)
| +- jinja2(install version:2.10.3 version range:>=2.10)
| | +- markupsafe(install version:1.1.1 version range:>=0.23)
| +- jsonschema(install version:2.6.0 version range:<3.0.0,>=2.6.0)
| +- pandas(install version:0.25.3 version range:>=0.25.0)
| +- py-healthcheck(install version:1.9.0 version range:>=1.9.0)
| | +- six(install version:1.13.0 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Ask your upstream project **_eve_** to loose the version range of **_urllib3_**.
2.	Fix your direct dependency to be **_eve<=0.9.0_**. I have checked this revision will not affect your downstream projects now.

@jlane93 Which solution do you prefer, 1 or 2?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by jlane9** [comment]
Just to be certain, your suggestion for 1 is to loosen the versioning on **urllib3** and not **werkzeug**?

**Comment by jlane9** [comment]
Also, it appears Eve has fixed the version for **werkzeug** because some of the newer versions have been breaking functionality.

https://github.com/pyeve/eve/issues/1267
https://github.com/pyeve/eve/issues/1325

**Comment by NeolithEra** [comment]
Could you add a new direct dependency **_werkzeug==0.15.4_**. I have checked this revision will not affect your downstream projects now.
Now, **_werkzeug 0.16.0_** is the actually installed version which is installed by **_flask_**. However, **_werkzeug 0.16.0_** does not satisfy **==0.15.4**.

**Comment by jlane9** [comment]
Thanks @NeolithEra I've pushed up changes that should resolve this. Also you uncovering this helped me find a breaking change with the newest version of faker 🙌
